### ISSUE TITLE
Notebook 3 - cannot run the decoder

### ISSUE THREAD

**Issue by janinaf** [themattinthehatt/behavenet#25]
I am just trying to get started with the decoder notebook, but I cannot run from the terminal either for the continuous or discrete states (the two errors are identical):

Traceback (most recent call last):
  File "behavenet/fitting/decoder_grid_search.py", line 116, in <module>
    hyperparams = get_all_params('grid_search')
  File "/Users/janinaf/Dropbox/behavenet/behavenet/fitting/hyperparam_utils.py", line 47, in get_all_params
    add_dependent_params(parser, namespace)
  File "/Users/janinaf/Dropbox/behavenet/behavenet/fitting/hyperparam_utils.py", line 106, in add_dependent_params
    if namespace.subsample_method != 'none':
AttributeError: 'Namespace' object has no attribute 'subsample_method'

Note: there is an error in the notebook, the name of the file is listed as:
decoding_grid_search
but it should be decod**er**_grid_search

**Comment by themattinthehatt** [comment]
thanks! the master branch has been updated (commit df57dfc)
